### ISSUE TITLE
Alignment of the Sign in icon and Dark Mode icon in the top Navbar

### ISSUE THREAD

**Issue by mahiiverse1** [mahiiverse1/booknbuy-website#4]
In the top navigation bar, the Sign In icon and the Dark Mode icon are not aligned in a single line. Anyone who would wish to fix it please let me know.

You are free to change the icons if you wish and remove the 'Dark mode!' written below the dark mode icon if you wish. Do not add any new feature simply make sure it aligns.

**Comment by YC-Kwan** [comment]
Can assign the issue to me? I will look into it

**Comment by mahiiverse1** [comment]
yes you can!
